name: Build Desktop App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Gunakan versi Node yang sesuai

      - name: Install dependencies
        run: npm ci # 'ci' lebih cepat dan andal untuk CI/CD

      - name: Generate Prisma Client
        run: npx prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Build application
        run: npm run build
        env: 
          NODE_ENV: production
          GH_TOKEN: ${{ secrets.GH_TOKEN }} 

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fb-automation-${{ matrix.os }}
          path: dist/